{{- if .Values.ingress.enabled }}
{{- $root := . -}}
{{- $first := true }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - http:
        paths:
          {{- range $svcName, $svc := .Values.services }}
          {{- if eq (include "app.isPublic" $svc) "true" }}
          {{- $port0 := index $svc.ports 0 }}
          - path: {{ if $first }}/{{ else }}/{{ $svcName }}{{ end }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.svcname" (list $root $svcName) }}
                port:
                  name: {{ $port0.name }}
          {{- $first = false }}
          {{- end }}
          {{- end }}
      {{- with .Values.ingress.host }}
      host: {{ . | quote }}
      {{- end }}
{{- end }}
