{{- $root := . -}}
{{- range $svcName, $svc := .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.svcname" (list $root $svcName) }}
  namespace: {{ $root.Values.namespace }}
  labels:
    {{- include "app.labels" (list $root $svcName) | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
