#!/usr/bin/env bash
# Shell twin of ansible/playbooks/postgres-client.yml: check the external database, run optional
# bootstrap SQL and push a runtime config file into the running pods.
#
# Inputs (env, from build/<provider>/<name>/configure.env):
#   NAMESPACE APP_NAME TARGET_SELECTOR CONTAINER PG_HOST PG_PORT PG_DATABASE PG_USER PG_SSLMODE
#   PASSWORD_SECRET PASSWORD_SECRET_KEY CHECK_CONNECTIVITY BOOTSTRAP_SQL RUNTIME_CONFIG_PATH
set -Eeuo pipefail
# shellcheck source=lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
apply_overrides "$@"
require_cmd kubectl psql pg_isready base64

: "${NAMESPACE:?}" "${TARGET_SELECTOR:?}" "${CONTAINER:?}" "${PG_HOST:?}" "${PG_DATABASE:?}" "${PG_USER:?}" \
  "${PASSWORD_SECRET:?}" "${PASSWORD_SECRET_KEY:?}"
PG_PORT="${PG_PORT:-5432}"
PG_SSLMODE="${PG_SSLMODE:-require}"
CHECK_CONNECTIVITY="${CHECK_CONNECTIVITY:-true}"
BOOTSTRAP_SQL="${BOOTSTRAP_SQL:-}"
RUNTIME_CONFIG_PATH="${RUNTIME_CONFIG_PATH:-/tmp/database.conf}"

secret_exists "$NAMESPACE" "$PASSWORD_SECRET" || die "Secret $NAMESPACE/$PASSWORD_SECRET not found (deploy.sh creates it from the cloud secret store)"
export PGHOST="$PG_HOST" PGPORT="$PG_PORT" PGDATABASE="$PG_DATABASE" PGUSER="$PG_USER" PGSSLMODE="$PG_SSLMODE" PGCONNECT_TIMEOUT=10
PGPASSWORD="$(secret_key "$NAMESPACE" "$PASSWORD_SECRET" "$PASSWORD_SECRET_KEY")"; export PGPASSWORD
[[ -n "$PGPASSWORD" ]] || die "key $PASSWORD_SECRET_KEY in Secret $PASSWORD_SECRET is empty"

if [[ "$CHECK_CONNECTIVITY" == "true" ]]; then
  log "checking $PG_HOST:$PG_PORT accepts connections"
  pg_isready -t 10 || die "database is not reachable from here (network policy / firewall / private endpoint?)"
  [[ "$(psql -X -A -t -c 'select 1' | tr -d '[:space:]')" == "1" ]] || die "SELECT 1 failed as $PG_USER on $PG_DATABASE"
  log "credentials OK"
fi

if [[ -n "$BOOTSTRAP_SQL" ]]; then
  [[ -f "$BOOTSTRAP_SQL" ]] || die "bootstrap SQL file not found: $BOOTSTRAP_SQL"
  log "running bootstrap SQL $BOOTSTRAP_SQL"
  psql -X -v ON_ERROR_STOP=1 -f "$BOOTSTRAP_SQL"
fi

mapfile -t pods < <(running_pods "$NAMESPACE" "$TARGET_SELECTOR")
[[ ${#pods[@]} -gt 0 ]] || die "no running pod matches $TARGET_SELECTOR in $NAMESPACE"

conf="$(mktemp -t database.conf.XXXXXX)"
trap 'rm -f "$conf"' EXIT
cat > "$conf" <<CONF
# generated by podkit postgres-client.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
host=$PG_HOST
port=$PG_PORT
dbname=$PG_DATABASE
user=$PG_USER
sslmode=$PG_SSLMODE
CONF

for pod in "${pods[@]}"; do
  kube cp "$conf" "$NAMESPACE/$pod:$RUNTIME_CONFIG_PATH" -c "$CONTAINER"   # needs tar in the image
  out="$(kube -n "$NAMESPACE" exec "$pod" -c "$CONTAINER" -- sh -c \
    "test -s '$RUNTIME_CONFIG_PATH' || exit 1; if command -v pg_isready >/dev/null 2>&1; then pg_isready -h \"\$PGHOST\" -p \"\$PGPORT\" -t 10; else echo 'pg_isready not in image; skipped in-pod check'; fi")"
  log "$pod: $out"
done
log "done"
