#!/usr/bin/env bash
# =============================================================================
# configure.sh — SECOND script: apply app.config.yaml to this host.
#
#   1. download every sources.files[] entry (host-files.tsv)  + verify sha256
#   2. write /etc/<app>/config.env from hosts.settings
#   3. (optional) run the app's containers with docker, using services[].ports
#      - pulls from sources.imageRegistry (ACR login via managed identity, no passwords)
#      - public ports are published on the host, cluster-only services are not
#
# Re-runnable: containers are recreated only if the image or settings changed.
# =============================================================================
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="${HOST_CONFIG:-$HERE/host-config.env}"
FILES="${HOST_FILES:-$HERE/host-files.tsv}"
# shellcheck disable=SC1090
source "$CONFIG"
: "${APP_NAME:?}" "${SERVICES:=}" "${IMAGE_REGISTRY:=}"
log() { printf '\n[configure %s] %s\n' "$(date +%H:%M:%S)" "$*"; }
[[ $EUID -eq 0 ]] || { echo "run as root (sudo $0)"; exit 1; }
[[ -f "/var/lib/$APP_NAME/setup.done" ]] || echo "warning: setup.sh has not run on this host yet"

# ---- 1. external files -----------------------------------------------------------
if [[ -s "$FILES" ]]; then
  log "downloading external files listed in $(basename "$FILES")"
  while IFS=$'\t' read -r name url dest mode sha; do
    [[ -z "$name" || "$name" == \#* ]] && continue
    mkdir -p "$(dirname "$dest")"
    tmp="$(mktemp)"
    if curl -fsSL --retry 3 --max-time 60 -o "$tmp" "$url"; then
      if [[ -n "$sha" && "$sha" != "-" ]]; then
        echo "$sha  $tmp" | sha256sum -c --quiet || { echo "  ✖ $name: sha256 mismatch, NOT installed"; rm -f "$tmp"; continue; }
      fi
      install -m "${mode:-0644}" "$tmp" "$dest"; rm -f "$tmp"
      echo "  ✔ $name -> $dest ($(wc -c <"$dest") bytes)"
    else
      echo "  ✖ $name: download failed from $url"; rm -f "$tmp"
    fi
  done < "$FILES"
else
  log "no external files configured"
fi

# ---- 2. settings ------------------------------------------------------------------
log "writing /etc/$APP_NAME/config.env"
mkdir -p "/etc/$APP_NAME"
{
  echo "# generated by configure.sh from app.config.yaml hosts.settings"
  echo "APP_NAME=$APP_NAME"; echo "APP_VERSION=${APP_VERSION:-}"
  for v in $(compgen -A variable SETTING_ | sort); do echo "${v#SETTING_}=${!v}"; done
} > "/etc/$APP_NAME/config.env"
chmod 0640 "/etc/$APP_NAME/config.env"
cat "/etc/$APP_NAME/config.env"

# ---- 3. containers ----------------------------------------------------------------
docker_ok() { command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; }

# ACR login WITHOUT a password: the VM's managed identity gets an AAD token from the
# instance metadata service and swaps it for a registry refresh token.
acr_login_managed_identity() {
  local registry="$1" aad refresh
  aad="$(curl -fsS -H Metadata:true --max-time 5 \
    'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F' | jq -r .access_token)" || return 1
  refresh="$(curl -fsS -X POST "https://${registry}/oauth2/exchange" \
    --data-urlencode grant_type=access_token --data-urlencode "service=${registry}" \
    --data-urlencode "access_token=${aad}" | jq -r .refresh_token)" || return 1
  printf '%s' "$refresh" | docker login "$registry" -u 00000000-0000-0000-0000-000000000000 --password-stdin
}

if [[ "${SETTING_RUN_DEMO_CONTAINERS:-false}" != "true" ]]; then
  log "RUN_DEMO_CONTAINERS is not 'true' — not starting containers"
elif ! docker_ok; then
  log "docker daemon not reachable on this host — skipping containers (fine inside a plain container)"
else
  if [[ -n "$IMAGE_REGISTRY" && "$IMAGE_REGISTRY" == *.azurecr.io ]]; then
    log "logging in to $IMAGE_REGISTRY with the VM managed identity"
    acr_login_managed_identity "$IMAGE_REGISTRY" || echo "  (managed-identity login failed; is AcrPull assigned to the VM?)"
  fi
  docker network inspect "$APP_NAME" >/dev/null 2>&1 || docker network create "$APP_NAME" >/dev/null
  for svc in $SERVICES; do
    n="$(echo "$svc" | tr '[:lower:]-' '[:upper:]_')"
    image_var="SERVICE_${n}_IMAGE"; host_var="SERVICE_${n}_HOST_PORT"
    cport_var="SERVICE_${n}_CONTAINER_PORT"; expose_var="SERVICE_${n}_EXPOSE"
    image="${!image_var}"; cname="$APP_NAME-$svc"
    log "service $svc -> container $cname ($image)"
    if [[ -n "$IMAGE_REGISTRY" ]]; then docker pull -q "$image" || { echo "  ✖ pull failed"; continue; }
    else docker image inspect "$image" >/dev/null 2>&1 || { echo "  ✖ local image $image not found (build it first)"; continue; }; fi
    args=(-d --restart unless-stopped --name "$cname" --network "$APP_NAME" --network-alias "$cname"
          -e "APP_NAME=$APP_NAME" -e "SERVICE_NAME=$svc" -e "APP_VERSION=${APP_VERSION:-}")
    [[ -f "$HERE/env/$svc.env" ]] && args+=(--env-file "$HERE/env/$svc.env")     # config values (may contain spaces)
    [[ -f "$HERE/secrets.env" ]] && args+=(--env-file "$HERE/secrets.env")      # secret values, if provided
    [[ "${!expose_var}" == "public" ]] && args+=(-p "${!host_var}:${!cport_var}")
    docker rm -f "$cname" >/dev/null 2>&1 || true
    docker run "${args[@]}" "$image" >/dev/null
    echo "  ✔ running ($( [[ "${!expose_var}" == "public" ]] && echo "host port ${!host_var}" || echo "internal only"))"
  done
  docker ps --filter "network=$APP_NAME" --format 'table {{.Names}}\t{{.Image}}\t{{.Ports}}\t{{.Status}}'
fi
mkdir -p "/var/lib/$APP_NAME" && date -u +%FT%TZ > "/var/lib/$APP_NAME/configure.done"
log "configure complete"
