---
run_demo_containers: "{{ (hostcfg.settings | default({})).RUN_DEMO_CONTAINERS | default('false') == 'true' }}"
docker_apt_packages: [docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin, python3-docker]
