{{- $root := . -}}
{{- range $svcName, $svc := .Values.services }}
{{- if $svc.secretKeys }}
{{- $vals := default dict (index $root.Values.secrets $svcName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.svcname" (list $root $svcName) }}-secrets
  namespace: {{ $root.Values.namespace }}
  labels:
    {{- include "app.labels" (list $root $svcName) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key := $svc.secretKeys }}
  {{ $key }}: {{ default "" (index $vals $key) | quote }}
  {{- end }}
{{- end }}
{{- end }}
