"""Write the generated output for one PodConfig/provider pair."""

from __future__ import annotations

import os
import shlex
import shutil
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

from . import hclfmt, k8s
from .hcl import to_hcl

TEMPLATES = Path(__file__).resolve().parent / "templates"

_env = Environment(
    loader=FileSystemLoader(str(TEMPLATES)),
    undefined=StrictUndefined,
    trim_blocks=True,
    lstrip_blocks=True,
    keep_trailing_newline=True,
)
_env.filters["hcl"] = to_hcl
_env.filters["sq"] = shlex.quote


class _Dumper(yaml.SafeDumper):
    """safe_dump, but multi-line strings use the readable literal block style (|)."""


def _represent_str(dumper: yaml.SafeDumper, data: str):
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_Dumper.add_representer(str, _represent_str)


def _dump_yaml(objs: list[dict]) -> str:
    return "\n".join(
        f"---\n{yaml.dump(o, Dumper=_Dumper, sort_keys=False, default_flow_style=False, width=120)}" for o in objs
    )


def _env_value(value) -> str:
    """Render a configure var for the shell (configure.env) flavour."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, tuple)):
        return ",".join(str(v) for v in value)
    text = str(value)
    if "{{ build_dir }}" in text:  # ansible-style placeholder -> shell variable
        return '"' + text.replace("{{ build_dir }}", "${BUILD_DIR}") + '"'
    return shlex.quote(text)


TEMPLATE_FILES = {
    "terraform/versions.tf.j2": "terraform/versions.tf",
    "terraform/providers.tf.j2": "terraform/providers.tf",
    "terraform/main.tf.j2": "terraform/main.tf",
    "terraform/variables.tf.j2": "terraform/variables.tf",
    "terraform/terraform.tfvars.j2": "terraform/terraform.tfvars",
    "terraform/outputs.tf.j2": "terraform/outputs.tf",
    "terraform/backend.tf.example.j2": "terraform/backend.tf.example",
    "scripts/pod.env.j2": "pod.env",
    "scripts/deploy.sh.j2": "deploy.sh",
    "scripts/destroy.sh.j2": "destroy.sh",
    "scripts/configure.sh.j2": "configure.sh",
    "README.md.j2": "README.md",
}


def generate(ctx: dict, out_dir: Path, *, force: bool = False) -> list[Path]:
    out_dir = Path(out_dir)
    if out_dir.exists() and any(out_dir.iterdir()) and not force:
        raise FileExistsError(f"{out_dir} is not empty (use --force to overwrite)")
    if out_dir.exists() and force:
        shutil.rmtree(out_dir)
    written: list[Path] = []

    def write(rel: str, content: str, executable: bool = False) -> None:
        path = out_dir / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        if executable:
            path.chmod(path.stat().st_mode | 0o111)
        written.append(path)

    for template, rel in TEMPLATE_FILES.items():
        text = _env.get_template(template).render(**ctx)
        if rel.endswith((".tf", ".tfvars", ".tf.example")):
            text = hclfmt.align(text)  # keeps `terraform fmt -check` happy
        write(rel, text, executable=rel.endswith(".sh"))

    write("k8s/serviceaccount.yaml", _dump_yaml([k8s.service_account(ctx)]))
    write("k8s/workload.yaml", _dump_yaml(k8s.workload_manifests(ctx)))

    conf = ctx["configure"]
    if conf["method"] != "none":
        write("ansible/vars.yml", "# Variables for " + str(conf["target"]) + " (generated by podgen)\n" + yaml.safe_dump(conf["vars"], sort_keys=False))
        lines = [f"# Variables for {conf['target']} (generated by podgen). Sourced by scripts/configure.sh."]
        for key, value in conf["vars"].items():
            lines.append(f"{key.upper()}={_env_value(value)}")
        write("configure.env", "\n".join(lines) + "\n")

    for rel, src in ctx["extra_files"].items():
        dest = out_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dest)
        written.append(dest)

    return [Path(os.path.relpath(p, out_dir)) for p in written]
